### ISSUE TITLE
Dark mode is not applied to the whole viewport

### ISSUE THREAD

**Issue by peterangelov** [jozzi/wordle-sk#3]
![Screenshot 2022-02-07 at 09 17 06](https://user-images.githubusercontent.com/1159427/152750165-2d4380fe-5d42-4ef5-97f5-2828bea064e6.png)

**Comment by jozzi** [comment]
Thanks for the feedback @peterangelov 
Does reload help with the issue as was fixing similar one yesterday so maybe you do not have the recent version.

If it persist please let me know the browser and version. Recent Chrome for OSX?

**Comment by peterangelov** [comment]
Reload did not help. Tried also Firefox and Safari.

Browser: Version 98.0.4758.80 (Official Build) (x86_64)
MacOs: 11.6 (20G165)

**Comment by jozzi** [comment]
@peterangelov Issue should be fixed now. Please try again if it works for you.

**Comment by peterangelov** [comment]
It works! 🎉

Thank you
